name: Export transport data
on:
  schedule:
    - cron:  '0 2 * * 4'
  push:
    branches-ignore:
      - 'gh-pages'

      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Setup python version
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    - name: Install osmium
      run: |
        sudo apt-get install osmium-tool
    - name: Install xsv
      run: |
        wget --quiet https://github.com/BurntSushi/xsv/releases/download/0.13.0/xsv-0.13.0-x86_64-unknown-linux-musl.tar.gz
        tar -zxvf xsv-0.13.0-x86_64-unknown-linux-musl.tar.gz
        pwd >> $GITHUB_PATH      
    - name: Install dependencies
      run: ./install.sh
    - name: Export data
      env:
        INTERLINE_EXTRACTS_API_KEY: ${{ secrets.INTERLINE_EXTRACTS_API_KEY }}    
      run: ./export_data.sh
    - name: Deploy
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: output
